<?php

namespace Demo\PizzaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    /**
     * Get the query for the
     * Knp Pagination
     *
     * @called
     * - AdminController::indexAction
     * @return query
     */
    public function getPaginationQuery()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('o')
            ->addSelect('o.id')
            ->addSelect('c.firstname')
            ->addSelect('c.lastname')
            ->addSelect('c.phone')
            ->addSelect('c.address')
            ->addSelect('o.ingredient1')
            ->addSelect('o.ingredient2')
            ->addSelect('o.ingredient3')
            ->addSelect('s.size')
            ->addSelect('o.delivered')
            ->from($this->getEntityName(), 'o')
            ->leftJoin('o.customer', 'c')
            ->leftJoin('o.size', 's')
            ->orderBy('o.id')
            ->getQuery();
    }
}
