<?php

namespace Demo\PizzaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizesRepository extends EntityRepository
{
    /**
     * Get Sizes array for
     * the Choice input
     *
     * @called
     * - OrderController::step2Action
     * @return array
     */
    public function getChoices()
    {
        // Size Results
        $results = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('s.id, s.size')
            ->from($this->getEntityName(), 's', 's.id')
            ->where('s.isActive = true')
            ->getQuery()
            ->getResult();

        // Choices Array
        $choices = array();
        foreach($results as $result)
        {
            $choices[$result['id']] = $result['size'];
        }

        // Free Memory
        unset($results);

        return $choices;
    }
}
